### ISSUE TITLE
UI for uploading new tasks to the Database

### ISSUE THREAD

**Issue by SethAngell** [ORNL-DataViz/DataVizTrials#2]
## Product Specs
Ability to:
- [x] Provide a tag that the entire set will be tested against
- [x] Upload up to 50 (?) images at once
- [x] Mark whether each photo is a yes or a no*

*There needs to be some way to specify which photos are correctly tagged, and which are meant to be marked as no. Two potential options are:
 - A second screen after the initial upload, which presents all of the photos with y/n boxes next to them for selection
 - Two separate ImageUpload fields marked "correct" and "incorrect" so that the folders can be uploaded to their respective points.

**Comment by sarahmathew** [comment]
I like the second option to tag pictures, it'll be easier. I think what's typically done for classifying data though is that a csv is created+uploaded where images and tags are paired.
