### ISSUE TITLE
*.jpeg / *.png to texture conversion

### ISSUE THREAD

**Issue by SethAngell** [ORNL-DataViz/DataVizTrials#4]
## Product Specs
All uploaded Images should be converted to DirectDraw Surface textures (.DDL). [Forum post for reference](https://answers.unity.com/questions/555984/can-you-load-dds-textures-during-runtime.html)

Should have the ability to:
- [x] Take in any .jpeg or .png file and convert to .DDS files (which are just a byte[] containers as far as I can tell)

**Comment by sarahmathew** [comment]
what i used: https://stackoverflow.com/questions/46944897/how-can-i-convert-a-dds-file-to-a-png-in-python
